//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace JGCompanion
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int aluminum = 0x7f020000;
            
            public const int amananth = 0x7f020001;
            
            public const int ammunition = 0x7f020002;
            
            public const int antimony = 0x7f020003;
            
            public const int armor = 0x7f020004;
            
            public const int background = 0x7f020005;
            
            public const int barium = 0x7f020006;
            
            public const int boron = 0x7f020007;
            
            public const int carbon = 0x7f020008;
            
            public const int cesium = 0x7f020009;
            
            public const int chemicals = 0x7f02000a;
            
            public const int chromium = 0x7f02000b;
            
            public const int cobalt = 0x7f02000c;
            
            public const int common_metals = 0x7f02000d;
            
            public const int composites = 0x7f02000e;
            
            public const int conflux_biomass = 0x7f02000f;
            
            public const int construction_materials = 0x7f020010;
            
            public const int copper = 0x7f020011;
            
            public const int cpus = 0x7f020012;
            
            public const int electronics = 0x7f020013;
            
            public const int erbium = 0x7f020014;
            
            public const int explosives = 0x7f020015;
            
            public const int faction_icon = 0x7f020016;
            
            public const int fiber_optics = 0x7f020017;
            
            public const int fuel_cells = 0x7f020018;
            
            public const int gallium = 0x7f020019;
            
            public const int gemwoods = 0x7f02001a;
            
            public const int germanium = 0x7f02001b;
            
            public const int gold = 0x7f02001c;
            
            public const int grain = 0x7f02001d;
            
            public const int gravitational_components = 0x7f02001e;
            
            public const int helium = 0x7f02001f;
            
            public const int hyperial = 0x7f020020;
            
            public const int ice = 0x7f020021;
            
            public const int Icon = 0x7f020022;
            
            public const int indium = 0x7f020023;
            
            public const int iridium = 0x7f020024;
            
            public const int iron = 0x7f020025;
            
            public const int jossh_background = 0x7f020026;
            
            public const int laser_components = 0x7f020027;
            
            public const int lithium = 0x7f020028;
            
            public const int machined_parts = 0x7f020029;
            
            public const int magnesium = 0x7f02002a;
            
            public const int magnetics = 0x7f02002b;
            
            public const int manufactured_foods = 0x7f02002c;
            
            public const int medical_supplies = 0x7f02002d;
            
            public const int molybdenum = 0x7f02002e;
            
            public const int natural_products = 0x7f02002f;
            
            public const int nitrogen = 0x7f020030;
            
            public const int octavia_light = 0x7f020031;
            
            public const int octavius = 0x7f020032;
            
            public const int OctaviusIcon = 0x7f020033;
            
            public const int optics = 0x7f020034;
            
            public const int organic_foods = 0x7f020035;
            
            public const int palladium = 0x7f020036;
            
            public const int phosphorous = 0x7f020037;
            
            public const int PilotDetailTextViewBlack = 0x7f020038;
            
            public const int PilotDetailTextViewDarkGray = 0x7f020039;
            
            public const int PilotDetailTextViewGray = 0x7f02003a;
            
            public const int PilotDetailTextViewInFlight = 0x7f02003b;
            
            public const int PilotDetailTextViewOnline = 0x7f02003c;
            
            public const int platinum = 0x7f02003d;
            
            public const int plutonium = 0x7f02003e;
            
            public const int power_converters = 0x7f02003f;
            
            public const int precious_metals = 0x7f020040;
            
            public const int prosthetics = 0x7f020041;
            
            public const int proximity_fuses = 0x7f020042;
            
            public const int quantar = 0x7f020043;
            
            public const int QuantarIcon = 0x7f020044;
            
            public const int quanus_ice = 0x7f020045;
            
            public const int radioactive_metals = 0x7f020046;
            
            public const int radium = 0x7f020047;
            
            public const int ram = 0x7f020048;
            
            public const int rf_transceivers = 0x7f020049;
            
            public const int semifluxors = 0x7f02004a;
            
            public const int silicon = 0x7f02004b;
            
            public const int silver = 0x7f02004c;
            
            public const int solrain = 0x7f02004d;
            
            public const int solrain_stout = 0x7f02004e;
            
            public const int SolrainIcon = 0x7f02004f;
            
            public const int synthetics = 0x7f020050;
            
            public const int textiles = 0x7f020051;
            
            public const int titanium = 0x7f020052;
            
            public const int tri = 0x7f020053;
            
            public const int uranium = 0x7f020054;
            
            public const int vanadium = 0x7f020055;
            
            public const int water = 0x7f020056;
            
            public const int x = 0x7f020057;
            
            public const int xenon = 0x7f020058;
            
            public const int zinc = 0x7f020059;
        }
        
        public sealed class Layouts
        {
            
            public const int ItemComponentsAdapter_Layout = 0x7f030000;
            
            public const int ItemComponentsAdapter_NoQty_Layout = 0x7f030001;
            
            public const int ItemDetailActivity_Layout = 0x7f030002;
            
            public const int ItemDetailsTabFragment_Blank_Layout = 0x7f030003;
            
            public const int ItemDetailsTabFragment_Capacitor_Layout = 0x7f030004;
            
            public const int ItemDetailsTabFragment_Commodity_Layout = 0x7f030005;
            
            public const int ItemDetailsTabFragment_ECM_Layout = 0x7f030006;
            
            public const int ItemDetailsTabFragment_Engine_Layout = 0x7f030007;
            
            public const int ItemDetailsTabFragment_Gun_Layout = 0x7f030008;
            
            public const int ItemDetailsTabFragment_Missile_Layout = 0x7f030009;
            
            public const int ItemDetailsTabFragment_MODx_Layout = 0x7f03000a;
            
            public const int ItemDetailsTabFragment_PowerPlant_Layout = 0x7f03000b;
            
            public const int ItemDetailsTabFragment_Radar_Layout = 0x7f03000c;
            
            public const int ItemDetailsTabFragment_Shield_Layout = 0x7f03000d;
            
            public const int ItemProducerComponentsAdapter_Layout = 0x7f03000e;
            
            public const int ItemProducersAdapter_Layout = 0x7f03000f;
            
            public const int ItemProducersTabFragment_Layout = 0x7f030010;
            
            public const int ItemStationStockAdapter_Layout = 0x7f030011;
            
            public const int ItemStationStockTabFragment_Layout = 0x7f030012;
            
            public const int ItemStocksActivity_Layout = 0x7f030013;
            
            public const int ItemStocksAdapter_Layout = 0x7f030014;
            
            public const int MainLayout = 0x7f030015;
            
            public const int OnlinePilotsActivity_Layout = 0x7f030016;
            
            public const int PilotDetailActivity_Layout = 0x7f030017;
            
            public const int PilotListAdapter_Layout = 0x7f030018;
            
            public const int PilotListCounterFragment_Layout = 0x7f030019;
            
            public const int PilotsStatsListFragment_Layout = 0x7f03001a;
            
            public const int PilotStatsAdapter_Layout = 0x7f03001b;
            
            public const int StationInventoryActivity_Layout = 0x7f03001c;
            
            public const int StationInventoryAdapter_Layout = 0x7f03001d;
            
            public const int StationInventoryListFragment_Layout = 0x7f03001e;
            
            public const int TopPilotsActivity_Layout = 0x7f03001f;
        }
        
        public sealed class Xmls
        {
            
            public const int preferences = 0x7f040000;
        }
        
        public sealed class Ids
        {
            
            public const int itemComponentName = 0x7f050035;
            
            public const int itemComponentQty = 0x7f050036;
            
            public const int itemDetailFragmentContainer = 0x7f050037;
            
            public const int txtItemDetailDescription = 0x7f050038;
            
            public const int txtItemDetailClassification = 0x7f050039;
            
            public const int txtItemDetailManufacturer = 0x7f05003a;
            
            public const int txtItemDetailTechLevel = 0x7f05003b;
            
            public const int txtItemDetailSize = 0x7f05003c;
            
            public const int txtItemDetailMass = 0x7f05003d;
            
            public const int txtItemDetailEfficiency = 0x7f05003e;
            
            public const int txtItemDetailCapacity = 0x7f05003f;
            
            public const int headingItemDetailComponents = 0x7f050040;
            
            public const int listItemDetailComponents = 0x7f050041;
            
            public const int txtItemDetailAbbr = 0x7f050042;
            
            public const int txtItemDetailMeltingPoint = 0x7f050043;
            
            public const int txtItemDetailGraviticSig = 0x7f050044;
            
            public const int txtItemDetailSensorLevel = 0x7f050045;
            
            public const int txtItemDetailPowerUsage = 0x7f050046;
            
            public const int txtItemDetailMaxThrust = 0x7f050047;
            
            public const int txtItemDetailVelocity = 0x7f050048;
            
            public const int txtItemDetailLife = 0x7f050049;
            
            public const int txtItemDetailRange = 0x7f05004a;
            
            public const int txtItemDetailDelay = 0x7f05004b;
            
            public const int txtItemDetailDamage = 0x7f05004c;
            
            public const int txtItemDetailEnergyUse = 0x7f05004d;
            
            public const int txtItemDetailAmmo = 0x7f05004e;
            
            public const int txtItemDetailThrust = 0x7f05004f;
            
            public const int txtItemDetailMaxPitch = 0x7f050050;
            
            public const int txtItemDetailMaxYaw = 0x7f050051;
            
            public const int txtItemDetailDrag = 0x7f050052;
            
            public const int txtItemDetailOutput = 0x7f050053;
            
            public const int txtItemDetailMaxRange = 0x7f050054;
            
            public const int txtItemDetailMaxRegenRate = 0x7f050055;
            
            public const int txtItemDetailMaxDeflect = 0x7f050056;
            
            public const int txtItemDetailBaseRate = 0x7f050057;
            
            public const int itemProducerComponentName = 0x7f050058;
            
            public const int itemProducerComponentQty = 0x7f050059;
            
            public const int itemProducerName = 0x7f05005a;
            
            public const int listProducerComponents = 0x7f05005b;
            
            public const int itemDetailProducersListView = 0x7f05005c;
            
            public const int itemStationName = 0x7f05005d;
            
            public const int itemStationQty = 0x7f05005e;
            
            public const int itemStationPrice = 0x7f05005f;
            
            public const int itemDetailInventoryListView = 0x7f050060;
            
            public const int itemStocksListView = 0x7f050061;
            
            public const int itemStockItemName = 0x7f050062;
            
            public const int itemStockQty = 0x7f050063;
            
            public const int btnMyPilotStats = 0x7f050064;
            
            public const int btnPilotStats = 0x7f050065;
            
            public const int btnOnlinePilots = 0x7f050066;
            
            public const int btnStationInventories = 0x7f050067;
            
            public const int btnItemStocks = 0x7f050068;
            
            public const int pilotsOnlineFragmentContainer = 0x7f050069;
            
            public const int txtPilotDetailOnlineStatus = 0x7f05006a;
            
            public const int txtPilotDetailLastOnline = 0x7f05006b;
            
            public const int txtPilotDetailRank = 0x7f05006c;
            
            public const int txtPilotDetailSquad = 0x7f05006d;
            
            public const int txtPilotDetailRegistry = 0x7f05006e;
            
            public const int txtPilotDetailExpToNextLevel = 0x7f05006f;
            
            public const int txtPilotDetailSolKills = 0x7f050070;
            
            public const int txtPilotDetailSolRating = 0x7f050071;
            
            public const int txtPilotDetailOctKills = 0x7f050072;
            
            public const int txtPilotDetailOctRating = 0x7f050073;
            
            public const int txtPilotDetailQuantKills = 0x7f050074;
            
            public const int txtPilotDetailQuantRating = 0x7f050075;
            
            public const int txtPilotDetailAmanRating = 0x7f050076;
            
            public const int txtPilotDetailHypRating = 0x7f050077;
            
            public const int txtPilotDetailTotalPilotKills = 0x7f050078;
            
            public const int txtPilotDetailBountyCollected = 0x7f050079;
            
            public const int txtPilotDetailBountyPerKill = 0x7f05007a;
            
            public const int txtPilotDetailDeaths = 0x7f05007b;
            
            public const int txtPilotDetailKillRatio = 0x7f05007c;
            
            public const int txtPilotDetailConfluxKills = 0x7f05007d;
            
            public const int txtPilotDetailGunshotsFired = 0x7f05007e;
            
            public const int txtPilotDetailGunshotsHit = 0x7f05007f;
            
            public const int txtPilotDetailGunAccuracy = 0x7f050080;
            
            public const int txtPilotDetailMissilesFired = 0x7f050081;
            
            public const int txtPilotDetailMissilesHit = 0x7f050082;
            
            public const int txtPilotDetailMissileAccuracy = 0x7f050083;
            
            public const int txtPilotDetailExperience = 0x7f050084;
            
            public const int txtPilotDetailCredits = 0x7f050085;
            
            public const int txtPilotDetailLaunches = 0x7f050086;
            
            public const int txtPilotDetailLandings = 0x7f050087;
            
            public const int txtPilotDetailDisconnects = 0x7f050088;
            
            public const int txtPilotDetailDutyHours = 0x7f050089;
            
            public const int txtPilotDetailMissionsTaken = 0x7f05008a;
            
            public const int txtPilotDetailMissionsCompleted = 0x7f05008b;
            
            public const int txtPilotDetailInsuranceRating = 0x7f05008c;
            
            public const int pilotName = 0x7f05008d;
            
            public const int pilotFaction = 0x7f05008e;
            
            public const int pilotListCounterTitle = 0x7f05008f;
            
            public const int pilotListCounterView = 0x7f050090;
            
            public const int pilotStatsTextTitle = 0x7f050091;
            
            public const int pilotStatsListView = 0x7f050092;
            
            public const int pilotStatName = 0x7f050093;
            
            public const int pilotStatFaction = 0x7f050094;
            
            public const int pilotStatValue = 0x7f050095;
            
            public const int stationInventoryFragmentContainer = 0x7f050096;
            
            public const int inventoryItemName = 0x7f050097;
            
            public const int inventoryItemQty = 0x7f050098;
            
            public const int inventoryItemPrice = 0x7f050099;
            
            public const int stationInventoryListView = 0x7f05009a;
            
            public const int pilotStatsFragmentContainer = 0x7f05009b;
            
            public const int settingMenuItem = 0x7f05009c;
        }
        
        public sealed class Menus
        {
            
            public const int MainActivityMenu = 0x7f060000;
        }
    }
}
