//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace JGCompanion
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int amananth = 0x7f020000;
            
            public const int background = 0x7f020001;
            
            public const int faction_icon = 0x7f020002;
            
            public const int hyperial = 0x7f020003;
            
            public const int Icon = 0x7f020004;
            
            public const int jossh_background = 0x7f020005;
            
            public const int octavius = 0x7f020006;
            
            public const int OctaviusIcon = 0x7f020007;
            
            public const int PilotDetailTextViewBlack = 0x7f020008;
            
            public const int PilotDetailTextViewDarkGray = 0x7f020009;
            
            public const int PilotDetailTextViewGray = 0x7f02000a;
            
            public const int PilotDetailTextViewInFlight = 0x7f02000b;
            
            public const int PilotDetailTextViewOnline = 0x7f02000c;
            
            public const int quantar = 0x7f02000d;
            
            public const int QuantarIcon = 0x7f02000e;
            
            public const int solrain = 0x7f02000f;
            
            public const int SolrainIcon = 0x7f020010;
            
            public const int tri = 0x7f020011;
        }
        
        public sealed class Layouts
        {
            
            public const int ItemComponentsAdapter_Layout = 0x7f030000;
            
            public const int ItemComponentsAdapter_NoQty_Layout = 0x7f030001;
            
            public const int ItemDetailActivity_Layout = 0x7f030002;
            
            public const int ItemDetailsTabFragment_Blank_Layout = 0x7f030003;
            
            public const int ItemDetailsTabFragment_Capacitor_Layout = 0x7f030004;
            
            public const int ItemDetailsTabFragment_Commodity_Layout = 0x7f030005;
            
            public const int ItemDetailsTabFragment_ECM_Layout = 0x7f030006;
            
            public const int ItemDetailsTabFragment_Engine_Layout = 0x7f030007;
            
            public const int ItemDetailsTabFragment_Gun_Layout = 0x7f030008;
            
            public const int ItemDetailsTabFragment_Missile_Layout = 0x7f030009;
            
            public const int ItemDetailsTabFragment_MODx_Layout = 0x7f03000a;
            
            public const int ItemDetailsTabFragment_PowerPlant_Layout = 0x7f03000b;
            
            public const int ItemDetailsTabFragment_Radar_Layout = 0x7f03000c;
            
            public const int ItemDetailsTabFragment_Shield_Layout = 0x7f03000d;
            
            public const int ItemProducerComponentsAdapter_Layout = 0x7f03000e;
            
            public const int ItemProducersAdapter_Layout = 0x7f03000f;
            
            public const int ItemProducersTabFragment_Layout = 0x7f030010;
            
            public const int ItemStationStockAdapter_Layout = 0x7f030011;
            
            public const int ItemStationStockTabFragment_Layout = 0x7f030012;
            
            public const int ItemStocksActivity_Layout = 0x7f030013;
            
            public const int ItemStocksAdapter_Layout = 0x7f030014;
            
            public const int MainLayout = 0x7f030015;
            
            public const int OnlinePilotsActivity_Layout = 0x7f030016;
            
            public const int PilotDetailActivity_Layout = 0x7f030017;
            
            public const int PilotListAdapter_Layout = 0x7f030018;
            
            public const int PilotListCounterFragment_Layout = 0x7f030019;
            
            public const int PilotsStatsListFragment_Layout = 0x7f03001a;
            
            public const int PilotStatsAdapter_Layout = 0x7f03001b;
            
            public const int StationInventoryActivity_Layout = 0x7f03001c;
            
            public const int StationInventoryAdapter_Layout = 0x7f03001d;
            
            public const int StationInventoryListFragment_Layout = 0x7f03001e;
            
            public const int TopPilotsActivity_Layout = 0x7f03001f;
        }
        
        public sealed class Xmls
        {
            
            public const int preferences = 0x7f040000;
        }
        
        public sealed class Ids
        {
            
            public const int itemComponentName = 0x7f050035;
            
            public const int itemComponentQty = 0x7f050036;
            
            public const int itemDetailFragmentContainer = 0x7f050037;
            
            public const int txtItemDetailDescription = 0x7f050038;
            
            public const int txtItemDetailClassification = 0x7f050039;
            
            public const int txtItemDetailManufacturer = 0x7f05003a;
            
            public const int txtItemDetailTechLevel = 0x7f05003b;
            
            public const int txtItemDetailSize = 0x7f05003c;
            
            public const int txtItemDetailMass = 0x7f05003d;
            
            public const int txtItemDetailEfficiency = 0x7f05003e;
            
            public const int txtItemDetailCapacity = 0x7f05003f;
            
            public const int headingItemDetailComponents = 0x7f050040;
            
            public const int listItemDetailComponents = 0x7f050041;
            
            public const int txtItemDetailAbbr = 0x7f050042;
            
            public const int txtItemDetailMeltingPoint = 0x7f050043;
            
            public const int txtItemDetailGraviticSig = 0x7f050044;
            
            public const int txtItemDetailSensorLevel = 0x7f050045;
            
            public const int txtItemDetailPowerUsage = 0x7f050046;
            
            public const int txtItemDetailMaxThrust = 0x7f050047;
            
            public const int txtItemDetailVelocity = 0x7f050048;
            
            public const int txtItemDetailLife = 0x7f050049;
            
            public const int txtItemDetailRange = 0x7f05004a;
            
            public const int txtItemDetailDelay = 0x7f05004b;
            
            public const int txtItemDetailDamage = 0x7f05004c;
            
            public const int txtItemDetailEnergyUse = 0x7f05004d;
            
            public const int txtItemDetailAmmo = 0x7f05004e;
            
            public const int txtItemDetailThrust = 0x7f05004f;
            
            public const int txtItemDetailMaxPitch = 0x7f050050;
            
            public const int txtItemDetailMaxYaw = 0x7f050051;
            
            public const int txtItemDetailDrag = 0x7f050052;
            
            public const int txtItemDetailOutput = 0x7f050053;
            
            public const int txtItemDetailMaxRange = 0x7f050054;
            
            public const int txtItemDetailMaxRegenRate = 0x7f050055;
            
            public const int txtItemDetailMaxDeflect = 0x7f050056;
            
            public const int txtItemDetailBaseRate = 0x7f050057;
            
            public const int itemProducerComponentName = 0x7f050058;
            
            public const int itemProducerComponentQty = 0x7f050059;
            
            public const int itemProducerName = 0x7f05005a;
            
            public const int listProducerComponents = 0x7f05005b;
            
            public const int itemDetailProducersListView = 0x7f05005c;
            
            public const int itemStationName = 0x7f05005d;
            
            public const int itemStationQty = 0x7f05005e;
            
            public const int itemStationPrice = 0x7f05005f;
            
            public const int itemDetailInventoryListView = 0x7f050060;
            
            public const int itemStocksListView = 0x7f050061;
            
            public const int itemStockItemName = 0x7f050062;
            
            public const int itemStockQty = 0x7f050063;
            
            public const int btnMyPilotStats = 0x7f050064;
            
            public const int btnPilotStats = 0x7f050065;
            
            public const int btnOnlinePilots = 0x7f050066;
            
            public const int btnStationInventories = 0x7f050067;
            
            public const int btnItemStocks = 0x7f050068;
            
            public const int pilotsOnlineFragmentContainer = 0x7f050069;
            
            public const int txtPilotDetailOnlineStatus = 0x7f05006a;
            
            public const int txtPilotDetailLastOnline = 0x7f05006b;
            
            public const int txtPilotDetailRank = 0x7f05006c;
            
            public const int txtPilotDetailSquad = 0x7f05006d;
            
            public const int txtPilotDetailRegistry = 0x7f05006e;
            
            public const int txtPilotDetailExpToNextLevel = 0x7f05006f;
            
            public const int txtPilotDetailSolKills = 0x7f050070;
            
            public const int txtPilotDetailSolRating = 0x7f050071;
            
            public const int txtPilotDetailOctKills = 0x7f050072;
            
            public const int txtPilotDetailOctRating = 0x7f050073;
            
            public const int txtPilotDetailQuantKills = 0x7f050074;
            
            public const int txtPilotDetailQuantRating = 0x7f050075;
            
            public const int txtPilotDetailAmanRating = 0x7f050076;
            
            public const int txtPilotDetailHypRating = 0x7f050077;
            
            public const int txtPilotDetailTotalPilotKills = 0x7f050078;
            
            public const int txtPilotDetailBountyCollected = 0x7f050079;
            
            public const int txtPilotDetailBountyPerKill = 0x7f05007a;
            
            public const int txtPilotDetailDeaths = 0x7f05007b;
            
            public const int txtPilotDetailKillRatio = 0x7f05007c;
            
            public const int txtPilotDetailConfluxKills = 0x7f05007d;
            
            public const int txtPilotDetailGunshotsFired = 0x7f05007e;
            
            public const int txtPilotDetailGunshotsHit = 0x7f05007f;
            
            public const int txtPilotDetailGunAccuracy = 0x7f050080;
            
            public const int txtPilotDetailMissilesFired = 0x7f050081;
            
            public const int txtPilotDetailMissilesHit = 0x7f050082;
            
            public const int txtPilotDetailMissileAccuracy = 0x7f050083;
            
            public const int txtPilotDetailExperience = 0x7f050084;
            
            public const int txtPilotDetailCredits = 0x7f050085;
            
            public const int txtPilotDetailLaunches = 0x7f050086;
            
            public const int txtPilotDetailLandings = 0x7f050087;
            
            public const int txtPilotDetailDisconnects = 0x7f050088;
            
            public const int txtPilotDetailDutyHours = 0x7f050089;
            
            public const int txtPilotDetailMissionsTaken = 0x7f05008a;
            
            public const int txtPilotDetailMissionsCompleted = 0x7f05008b;
            
            public const int txtPilotDetailInsuranceRating = 0x7f05008c;
            
            public const int pilotName = 0x7f05008d;
            
            public const int pilotFaction = 0x7f05008e;
            
            public const int pilotListCounterTitle = 0x7f05008f;
            
            public const int pilotListCounterView = 0x7f050090;
            
            public const int pilotStatsTextTitle = 0x7f050091;
            
            public const int pilotStatsListView = 0x7f050092;
            
            public const int pilotStatName = 0x7f050093;
            
            public const int pilotStatFaction = 0x7f050094;
            
            public const int pilotStatValue = 0x7f050095;
            
            public const int stationInventoryFragmentContainer = 0x7f050096;
            
            public const int inventoryItemName = 0x7f050097;
            
            public const int inventoryItemQty = 0x7f050098;
            
            public const int inventoryItemPrice = 0x7f050099;
            
            public const int stationInventoryListView = 0x7f05009a;
            
            public const int pilotStatsFragmentContainer = 0x7f05009b;
            
            public const int settingMenuItem = 0x7f05009c;
        }
        
        public sealed class Menus
        {
            
            public const int MainActivityMenu = 0x7f060000;
        }
    }
}
