//------------------------------------------------------------------------------
// This file is automatically generated by dot42
//------------------------------------------------------------------------------

namespace JGCompanion
{
    using System;
    
    
    public sealed class R
    {
        
        public sealed class Drawables
        {
            
            public const int abattis = 0x7f020000;
            
            public const int adventa = 0x7f020001;
            
            public const int alembic = 0x7f020002;
            
            public const int alpaa = 0x7f020003;
            
            public const int aluminum = 0x7f020004;
            
            public const int amananth = 0x7f020005;
            
            public const int ammunition = 0x7f020006;
            
            public const int ammunition_shop = 0x7f020007;
            
            public const int antagonizer = 0x7f020008;
            
            public const int antiflux = 0x7f020009;
            
            public const int antimony = 0x7f02000a;
            
            public const int armor = 0x7f02000b;
            
            public const int background = 0x7f02000c;
            
            public const int banker = 0x7f02000d;
            
            public const int barium = 0x7f02000e;
            
            public const int barrak = 0x7f02000f;
            
            public const int bcuoct = 0x7f020010;
            
            public const int bcuquan = 0x7f020011;
            
            public const int bcusol = 0x7f020012;
            
            public const int beholder = 0x7f020013;
            
            public const int bender = 0x7f020014;
            
            public const int boron = 0x7f020015;
            
            public const int broker = 0x7f020016;
            
            public const int buildkit_2 = 0x7f020017;
            
            public const int buildkit_4 = 0x7f020018;
            
            public const int buildkit_8 = 0x7f020019;
            
            public const int bullseye = 0x7f02001a;
            
            public const int burn = 0x7f02001b;
            
            public const int burn_mkii = 0x7f02001c;
            
            public const int calefactor = 0x7f02001d;
            
            public const int calypso = 0x7f02001e;
            
            public const int canopy = 0x7f02001f;
            
            public const int carbon = 0x7f020020;
            
            public const int cardoia = 0x7f020021;
            
            public const int carrier = 0x7f020022;
            
            public const int cascade = 0x7f020023;
            
            public const int caster = 0x7f020024;
            
            public const int centerfuge_mki = 0x7f020025;
            
            public const int centerfuge_mkii = 0x7f020026;
            
            public const int centerfuge_mkiii = 0x7f020027;
            
            public const int centerfuge_mkiv = 0x7f020028;
            
            public const int centerfuge_mkv = 0x7f020029;
            
            public const int cesium = 0x7f02002a;
            
            public const int chemicals = 0x7f02002b;
            
            public const int chime = 0x7f02002c;
            
            public const int chromium = 0x7f02002d;
            
            public const int clarifier = 0x7f02002e;
            
            public const int cobalt = 0x7f02002f;
            
            public const int cobra = 0x7f020030;
            
            public const int collector = 0x7f020031;
            
            public const int common_metals = 0x7f020032;
            
            public const int composites = 0x7f020033;
            
            public const int conflux_biomass = 0x7f020034;
            
            public const int construction_materials = 0x7f020035;
            
            public const int contender = 0x7f020036;
            
            public const int contender_xl = 0x7f020037;
            
            public const int contender_xpr = 0x7f020038;
            
            public const int copper = 0x7f020039;
            
            public const int cpus = 0x7f02003a;
            
            public const int cracker = 0x7f02003b;
            
            public const int creeper = 0x7f02003c;
            
            public const int cutlass = 0x7f02003d;
            
            public const int cyclops = 0x7f02003e;
            
            public const int dealer = 0x7f02003f;
            
            public const int deceptor = 0x7f020040;
            
            public const int deepol = 0x7f020041;
            
            public const int deepradar = 0x7f020042;
            
            public const int defier = 0x7f020043;
            
            public const int deflector = 0x7f020044;
            
            public const int displacer = 0x7f020045;
            
            public const int distorter = 0x7f020046;
            
            public const int docking_computer = 0x7f020047;
            
            public const int doorbell = 0x7f020048;
            
            public const int dream = 0x7f020049;
            
            public const int droptank = 0x7f02004a;
            
            public const int duelist = 0x7f02004b;
            
            public const int duster = 0x7f02004c;
            
            public const int echo = 0x7f02004d;
            
            public const int electronics = 0x7f02004e;
            
            public const int erbium = 0x7f02004f;
            
            public const int excavator = 0x7f020050;
            
            public const int explosives = 0x7f020051;
            
            public const int faction_icon = 0x7f020052;
            
            public const int featherfire = 0x7f020053;
            
            public const int fiber_optics = 0x7f020054;
            
            public const int financier = 0x7f020055;
            
            public const int financier_mkii = 0x7f020056;
            
            public const int flail = 0x7f020057;
            
            public const int flashfire = 0x7f020058;
            
            public const int flatiron = 0x7f020059;
            
            public const int fuel_cells = 0x7f02005a;
            
            public const int fuelscoop = 0x7f02005b;
            
            public const int gallium = 0x7f02005c;
            
            public const int gatherer = 0x7f02005d;
            
            public const int gemwoods = 0x7f02005e;
            
            public const int germ = 0x7f02005f;
            
            public const int germanium = 0x7f020060;
            
            public const int ghost = 0x7f020061;
            
            public const int glaive = 0x7f020062;
            
            public const int gold = 0x7f020063;
            
            public const int grain = 0x7f020064;
            
            public const int grave_robber = 0x7f020065;
            
            public const int gravitational_components = 0x7f020066;
            
            public const int guardian = 0x7f020067;
            
            public const int guzzler = 0x7f020068;
            
            public const int hall_monitor = 0x7f020069;
            
            public const int hammer = 0x7f02006a;
            
            public const int harvester = 0x7f02006b;
            
            public const int hatchet = 0x7f02006c;
            
            public const int haven = 0x7f02006d;
            
            public const int hawkeye = 0x7f02006e;
            
            public const int helium = 0x7f02006f;
            
            public const int hellrazor = 0x7f020070;
            
            public const int himelea = 0x7f020071;
            
            public const int hitman = 0x7f020072;
            
            public const int hyperial = 0x7f020073;
            
            public const int ice = 0x7f020074;
            
            public const int Icon = 0x7f020075;
            
            public const int illuminator = 0x7f020076;
            
            public const int impeler = 0x7f020077;
            
            public const int indium = 0x7f020078;
            
            public const int injustice = 0x7f020079;
            
            public const int insight = 0x7f02007a;
            
            public const int instigator = 0x7f02007b;
            
            public const int intimidator = 0x7f02007c;
            
            public const int iridium = 0x7f02007d;
            
            public const int iron = 0x7f02007e;
            
            public const int ivy = 0x7f02007f;
            
            public const int jammer = 0x7f020080;
            
            public const int jar = 0x7f020081;
            
            public const int jossh_background = 0x7f020082;
            
            public const int jug = 0x7f020083;
            
            public const int kataka = 0x7f020084;
            
            public const int keytso = 0x7f020085;
            
            public const int knocker = 0x7f020086;
            
            public const int kydango = 0x7f020087;
            
            public const int lance = 0x7f020088;
            
            public const int landlord = 0x7f020089;
            
            public const int laser_components = 0x7f02008a;
            
            public const int lastlight = 0x7f02008b;
            
            public const int liana = 0x7f02008c;
            
            public const int liar = 0x7f02008d;
            
            public const int lifeline = 0x7f02008e;
            
            public const int lightfire = 0x7f02008f;
            
            public const int lithium = 0x7f020090;
            
            public const int long_sword = 0x7f020091;
            
            public const int machined_parts = 0x7f020092;
            
            public const int magnesium = 0x7f020093;
            
            public const int magnetics = 0x7f020094;
            
            public const int makk = 0x7f020095;
            
            public const int mana = 0x7f020096;
            
            public const int mantra = 0x7f020097;
            
            public const int manufactured_foods = 0x7f020098;
            
            public const int market_warehouse = 0x7f020099;
            
            public const int maul = 0x7f02009a;
            
            public const int medical_supplies = 0x7f02009b;
            
            public const int mitoria = 0x7f02009c;
            
            public const int mitoria_plus = 0x7f02009d;
            
            public const int mitorias = 0x7f02009e;
            
            public const int ml_amplifier = 0x7f02009f;
            
            public const int molybdenum = 0x7f0200a0;
            
            public const int money = 0x7f0200a1;
            
            public const int morning_star = 0x7f0200a2;
            
            public const int mortar = 0x7f0200a3;
            
            public const int natural_products = 0x7f0200a4;
            
            public const int needle = 0x7f0200a5;
            
            public const int night_watchman = 0x7f0200a6;
            
            public const int nitrogen = 0x7f0200a7;
            
            public const int nocknock = 0x7f0200a8;
            
            public const int nova_mki = 0x7f0200a9;
            
            public const int nubbler = 0x7f0200aa;
            
            public const int octavia_light = 0x7f0200ab;
            
            public const int octavius = 0x7f0200ac;
            
            public const int OctaviusIcon = 0x7f0200ad;
            
            public const int omnus = 0x7f0200ae;
            
            public const int opal = 0x7f0200af;
            
            public const int optics = 0x7f0200b0;
            
            public const int optima = 0x7f0200b1;
            
            public const int oracle = 0x7f0200b2;
            
            public const int ore_silo = 0x7f0200b3;
            
            public const int organic_foods = 0x7f0200b4;
            
            public const int oteca = 0x7f0200b5;
            
            public const int outlet = 0x7f0200b6;
            
            public const int outlook = 0x7f0200b7;
            
            public const int palladium = 0x7f0200b8;
            
            public const int peeler = 0x7f0200b9;
            
            public const int phosphorous = 0x7f0200ba;
            
            public const int PilotDetailTextViewBlack = 0x7f0200bb;
            
            public const int PilotDetailTextViewDarkGray = 0x7f0200bc;
            
            public const int PilotDetailTextViewGray = 0x7f0200bd;
            
            public const int PilotDetailTextViewInFlight = 0x7f0200be;
            
            public const int PilotDetailTextViewOnline = 0x7f0200bf;
            
            public const int pint = 0x7f0200c0;
            
            public const int platinum = 0x7f0200c1;
            
            public const int plutonium = 0x7f0200c2;
            
            public const int pod = 0x7f0200c3;
            
            public const int power_converters = 0x7f0200c4;
            
            public const int prayer = 0x7f0200c5;
            
            public const int precious_metals = 0x7f0200c6;
            
            public const int propulser = 0x7f0200c7;
            
            public const int prospector = 0x7f0200c8;
            
            public const int prosthetics = 0x7f0200c9;
            
            public const int proximity_fuses = 0x7f0200ca;
            
            public const int purgatory = 0x7f0200cb;
            
            public const int pusher = 0x7f0200cc;
            
            public const int pwd100 = 0x7f0200cd;
            
            public const int quantar = 0x7f0200ce;
            
            public const int QuantarIcon = 0x7f0200cf;
            
            public const int quanus_ice = 0x7f0200d0;
            
            public const int radioactive_metals = 0x7f0200d1;
            
            public const int radium = 0x7f0200d2;
            
            public const int rake = 0x7f0200d3;
            
            public const int ram = 0x7f0200d4;
            
            public const int rapier = 0x7f0200d5;
            
            public const int rasp = 0x7f0200d6;
            
            public const int reaper = 0x7f0200d7;
            
            public const int refueling_tank = 0x7f0200d8;
            
            public const int repair_shop = 0x7f0200d9;
            
            public const int resistor = 0x7f0200da;
            
            public const int respect = 0x7f0200db;
            
            public const int rf_transceivers = 0x7f0200dc;
            
            public const int rocky = 0x7f0200dd;
            
            public const int root = 0x7f0200de;
            
            public const int rotacol = 0x7f0200df;
            
            public const int rush = 0x7f0200e0;
            
            public const int sabre = 0x7f0200e1;
            
            public const int sc15 = 0x7f0200e2;
            
            public const int screwdriver = 0x7f0200e3;
            
            public const int se15 = 0x7f0200e4;
            
            public const int seabear_e = 0x7f0200e5;
            
            public const int seed = 0x7f0200e6;
            
            public const int semifluxors = 0x7f0200e7;
            
            public const int senator = 0x7f0200e8;
            
            public const int sentinel = 0x7f0200e9;
            
            public const int sentry = 0x7f0200ea;
            
            public const int serializer = 0x7f0200eb;
            
            public const int shade = 0x7f0200ec;
            
            public const int shard = 0x7f0200ed;
            
            public const int shark = 0x7f0200ee;
            
            public const int shelter = 0x7f0200ef;
            
            public const int shepherd = 0x7f0200f0;
            
            public const int ship_hangar = 0x7f0200f1;
            
            public const int shroud = 0x7f0200f2;
            
            public const int silicon = 0x7f0200f3;
            
            public const int silver = 0x7f0200f4;
            
            public const int sirrus = 0x7f0200f5;
            
            public const int sledge = 0x7f0200f6;
            
            public const int smacker = 0x7f0200f7;
            
            public const int solrain = 0x7f0200f8;
            
            public const int solrain_stout = 0x7f0200f9;
            
            public const int SolrainIcon = 0x7f0200fa;
            
            public const int sp16 = 0x7f0200fb;
            
            public const int spear = 0x7f0200fc;
            
            public const int specter = 0x7f0200fd;
            
            public const int spitfire = 0x7f0200fe;
            
            public const int sponge = 0x7f0200ff;
            
            public const int spore = 0x7f020100;
            
            public const int sport = 0x7f020101;
            
            public const int sport_lp = 0x7f020102;
            
            public const int sport_plus = 0x7f020103;
            
            public const int spud = 0x7f020104;
            
            public const int sr9 = 0x7f020105;
            
            public const int ss13 = 0x7f020106;
            
            public const int stiletto = 0x7f020107;
            
            public const int stinger = 0x7f020108;
            
            public const int storage_warehouse = 0x7f020109;
            
            public const int straker = 0x7f02010a;
            
            public const int summoner = 0x7f02010b;
            
            public const int sw28 = 0x7f02010c;
            
            public const int synthetics = 0x7f02010d;
            
            public const int tangent = 0x7f02010e;
            
            public const int tank = 0x7f02010f;
            
            public const int textiles = 0x7f020110;
            
            public const int thief = 0x7f020111;
            
            public const int thorn = 0x7f020112;
            
            public const int titanium = 0x7f020113;
            
            public const int travant = 0x7f020114;
            
            public const int travant_plus = 0x7f020115;
            
            public const int tri = 0x7f020116;
            
            public const int tric1 = 0x7f020117;
            
            public const int trip1 = 0x7f020118;
            
            public const int uranium = 0x7f020119;
            
            public const int utterance = 0x7f02011a;
            
            public const int vanadium = 0x7f02011b;
            
            public const int vantage = 0x7f02011c;
            
            public const int vapor = 0x7f02011d;
            
            public const int vector = 0x7f02011e;
            
            public const int vine = 0x7f02011f;
            
            public const int vtc_i = 0x7f020120;
            
            public const int warden = 0x7f020121;
            
            public const int warper = 0x7f020122;
            
            public const int water = 0x7f020123;
            
            public const int wayfinder = 0x7f020124;
            
            public const int whistle = 0x7f020125;
            
            public const int witness = 0x7f020126;
            
            public const int wraith = 0x7f020127;
            
            public const int x0013s = 0x7f020128;
            
            public const int x1901l = 0x7f020129;
            
            public const int x3555l = 0x7f02012a;
            
            public const int x4533l = 0x7f02012b;
            
            public const int x7770l = 0x7f02012c;
            
            public const int x8821l = 0x7f02012d;
            
            public const int x9450c = 0x7f02012e;
            
            public const int xenon = 0x7f02012f;
            
            public const int zinc = 0x7f020130;
        }
        
        public sealed class Layouts
        {
            
            public const int ItemComponentsAdapter_Layout = 0x7f030000;
            
            public const int ItemComponentsAdapter_NoQty_Layout = 0x7f030001;
            
            public const int ItemDetailActivity_Layout = 0x7f030002;
            
            public const int ItemDetailsTabFragment_Blank_Layout = 0x7f030003;
            
            public const int ItemDetailsTabFragment_Capacitor_Layout = 0x7f030004;
            
            public const int ItemDetailsTabFragment_Commodity_Layout = 0x7f030005;
            
            public const int ItemDetailsTabFragment_ECM_Layout = 0x7f030006;
            
            public const int ItemDetailsTabFragment_Engine_Layout = 0x7f030007;
            
            public const int ItemDetailsTabFragment_Gun_Layout = 0x7f030008;
            
            public const int ItemDetailsTabFragment_Missile_Layout = 0x7f030009;
            
            public const int ItemDetailsTabFragment_MODx_Layout = 0x7f03000a;
            
            public const int ItemDetailsTabFragment_PowerPlant_Layout = 0x7f03000b;
            
            public const int ItemDetailsTabFragment_Radar_Layout = 0x7f03000c;
            
            public const int ItemDetailsTabFragment_Shield_Layout = 0x7f03000d;
            
            public const int ItemProducerComponentsAdapter_Layout = 0x7f03000e;
            
            public const int ItemProducersAdapter_Layout = 0x7f03000f;
            
            public const int ItemProducersTabFragment_Layout = 0x7f030010;
            
            public const int ItemStationStockAdapter_Layout = 0x7f030011;
            
            public const int ItemStationStockTabFragment_Layout = 0x7f030012;
            
            public const int ItemStocksActivity_Layout = 0x7f030013;
            
            public const int ItemStocksAdapter_Layout = 0x7f030014;
            
            public const int MainLayout = 0x7f030015;
            
            public const int OnlinePilotsActivity_Layout = 0x7f030016;
            
            public const int PilotDetailActivity_Layout = 0x7f030017;
            
            public const int PilotListAdapter_Layout = 0x7f030018;
            
            public const int PilotListCounterFragment_Layout = 0x7f030019;
            
            public const int PilotsStatsListFragment_Layout = 0x7f03001a;
            
            public const int PilotStatsAdapter_Layout = 0x7f03001b;
            
            public const int StationInventoryActivity_Layout = 0x7f03001c;
            
            public const int StationInventoryAdapter_Layout = 0x7f03001d;
            
            public const int StationInventoryListFragment_Layout = 0x7f03001e;
            
            public const int TopPilotsActivity_Layout = 0x7f03001f;
        }
        
        public sealed class Xmls
        {
            
            public const int preferences = 0x7f040000;
        }
        
        public sealed class Ids
        {
            
            public const int itemComponentName = 0x7f050035;
            
            public const int itemComponentQty = 0x7f050036;
            
            public const int itemDetailFragmentContainer = 0x7f050037;
            
            public const int txtItemDetailDescription = 0x7f050038;
            
            public const int txtItemDetailClassification = 0x7f050039;
            
            public const int txtItemDetailManufacturer = 0x7f05003a;
            
            public const int txtItemDetailTechLevel = 0x7f05003b;
            
            public const int txtItemDetailSize = 0x7f05003c;
            
            public const int txtItemDetailMass = 0x7f05003d;
            
            public const int txtItemDetailEfficiency = 0x7f05003e;
            
            public const int txtItemDetailCapacity = 0x7f05003f;
            
            public const int headingItemDetailComponents = 0x7f050040;
            
            public const int listItemDetailComponents = 0x7f050041;
            
            public const int txtItemDetailAbbr = 0x7f050042;
            
            public const int txtItemDetailMeltingPoint = 0x7f050043;
            
            public const int txtItemDetailGraviticSig = 0x7f050044;
            
            public const int txtItemDetailSensorLevel = 0x7f050045;
            
            public const int txtItemDetailPowerUsage = 0x7f050046;
            
            public const int txtItemDetailMaxThrust = 0x7f050047;
            
            public const int txtItemDetailVelocity = 0x7f050048;
            
            public const int txtItemDetailLife = 0x7f050049;
            
            public const int txtItemDetailRange = 0x7f05004a;
            
            public const int txtItemDetailDelay = 0x7f05004b;
            
            public const int txtItemDetailDamage = 0x7f05004c;
            
            public const int txtItemDetailEnergyUse = 0x7f05004d;
            
            public const int txtItemDetailAmmo = 0x7f05004e;
            
            public const int txtItemDetailThrust = 0x7f05004f;
            
            public const int txtItemDetailMaxPitch = 0x7f050050;
            
            public const int txtItemDetailMaxYaw = 0x7f050051;
            
            public const int txtItemDetailDrag = 0x7f050052;
            
            public const int txtItemDetailOutput = 0x7f050053;
            
            public const int txtItemDetailMaxRange = 0x7f050054;
            
            public const int txtItemDetailMaxRegenRate = 0x7f050055;
            
            public const int txtItemDetailMaxDeflect = 0x7f050056;
            
            public const int txtItemDetailBaseRate = 0x7f050057;
            
            public const int itemProducerComponentName = 0x7f050058;
            
            public const int itemProducerComponentQty = 0x7f050059;
            
            public const int itemProducerName = 0x7f05005a;
            
            public const int listProducerComponents = 0x7f05005b;
            
            public const int itemDetailProducersListView = 0x7f05005c;
            
            public const int itemStationName = 0x7f05005d;
            
            public const int itemStationQty = 0x7f05005e;
            
            public const int itemStationPrice = 0x7f05005f;
            
            public const int itemDetailInventoryListView = 0x7f050060;
            
            public const int itemStocksListView = 0x7f050061;
            
            public const int itemStockItemName = 0x7f050062;
            
            public const int itemStockQty = 0x7f050063;
            
            public const int btnMyPilotStats = 0x7f050064;
            
            public const int btnPilotStats = 0x7f050065;
            
            public const int btnOnlinePilots = 0x7f050066;
            
            public const int btnStationInventories = 0x7f050067;
            
            public const int btnItemStocks = 0x7f050068;
            
            public const int pilotsOnlineFragmentContainer = 0x7f050069;
            
            public const int txtPilotDetailOnlineStatus = 0x7f05006a;
            
            public const int txtPilotDetailLastOnline = 0x7f05006b;
            
            public const int txtPilotDetailRank = 0x7f05006c;
            
            public const int txtPilotDetailSquad = 0x7f05006d;
            
            public const int txtPilotDetailRegistry = 0x7f05006e;
            
            public const int txtPilotDetailExpToNextLevel = 0x7f05006f;
            
            public const int txtPilotDetailSolKills = 0x7f050070;
            
            public const int txtPilotDetailSolRating = 0x7f050071;
            
            public const int txtPilotDetailOctKills = 0x7f050072;
            
            public const int txtPilotDetailOctRating = 0x7f050073;
            
            public const int txtPilotDetailQuantKills = 0x7f050074;
            
            public const int txtPilotDetailQuantRating = 0x7f050075;
            
            public const int txtPilotDetailAmanRating = 0x7f050076;
            
            public const int txtPilotDetailHypRating = 0x7f050077;
            
            public const int txtPilotDetailTotalPilotKills = 0x7f050078;
            
            public const int txtPilotDetailBountyCollected = 0x7f050079;
            
            public const int txtPilotDetailBountyPerKill = 0x7f05007a;
            
            public const int txtPilotDetailDeaths = 0x7f05007b;
            
            public const int txtPilotDetailKillRatio = 0x7f05007c;
            
            public const int txtPilotDetailConfluxKills = 0x7f05007d;
            
            public const int txtPilotDetailGunshotsFired = 0x7f05007e;
            
            public const int txtPilotDetailGunshotsHit = 0x7f05007f;
            
            public const int txtPilotDetailGunAccuracy = 0x7f050080;
            
            public const int txtPilotDetailMissilesFired = 0x7f050081;
            
            public const int txtPilotDetailMissilesHit = 0x7f050082;
            
            public const int txtPilotDetailMissileAccuracy = 0x7f050083;
            
            public const int txtPilotDetailExperience = 0x7f050084;
            
            public const int txtPilotDetailCredits = 0x7f050085;
            
            public const int txtPilotDetailLaunches = 0x7f050086;
            
            public const int txtPilotDetailLandings = 0x7f050087;
            
            public const int txtPilotDetailDisconnects = 0x7f050088;
            
            public const int txtPilotDetailDutyHours = 0x7f050089;
            
            public const int txtPilotDetailMissionsTaken = 0x7f05008a;
            
            public const int txtPilotDetailMissionsCompleted = 0x7f05008b;
            
            public const int txtPilotDetailInsuranceRating = 0x7f05008c;
            
            public const int pilotName = 0x7f05008d;
            
            public const int pilotFaction = 0x7f05008e;
            
            public const int pilotListCounterTitle = 0x7f05008f;
            
            public const int pilotListCounterView = 0x7f050090;
            
            public const int pilotStatsTextTitle = 0x7f050091;
            
            public const int pilotStatsListView = 0x7f050092;
            
            public const int pilotStatName = 0x7f050093;
            
            public const int pilotStatFaction = 0x7f050094;
            
            public const int pilotStatValue = 0x7f050095;
            
            public const int stationInventoryFragmentContainer = 0x7f050096;
            
            public const int inventoryItemName = 0x7f050097;
            
            public const int inventoryItemQty = 0x7f050098;
            
            public const int inventoryItemPrice = 0x7f050099;
            
            public const int stationInventoryListView = 0x7f05009a;
            
            public const int pilotStatsFragmentContainer = 0x7f05009b;
            
            public const int settingMenuItem = 0x7f05009c;
        }
        
        public sealed class Menus
        {
            
            public const int MainActivityMenu = 0x7f060000;
        }
    }
}
